# Tệp cấu hình dự án Flutter (pubspec.yaml):
# Quản lý thông tin dự án, phiên bản SDK và cấu hình thay đổi icon ứng dụng.
# Khai báo các gói thư viện cốt lõi: quản lý trạng thái (provider), điều hướng (go_router), lưu trữ cục bộ (hive), gọi API (http), vẽ biểu đồ (fl_chart), và các tiện ích khác (intl, image_picker).
name: quan_ly_chi_tieu
description: Do an Quan ly chi tieu ca nhan.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.12.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  go_router: ^14.2.0 
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  image_picker: ^1.2.3
  flutter_animate: ^4.5.0
  shared_preferences: ^2.5.5
  uuid: ^4.6.0
  fl_chart: ^1.2.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"